# Generated by Django 4.1.1 on 2022-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
        migrations.AddField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='label',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
